export const GET_CIKISLAR = "GET_CIKISLAR";
export const DELETE_CIKIS = "DELETE_CIKIS";
export const UPDATE_CIKIS = "UPDATE_CIKIS";
export const POST_CIKIS = "POST_CIKIS";
export const SHOW_CIKIS_DETAIL_FORM = "SHOW_CIKIS_DETAIL_FORM";
export const SET_SELECTED_CIKIS = "SET_SELECTED_CIKIS";