export const GET_GIRISLER = "GET_GIRISLER";
export const DELETE_GIRIS = "DELETE_GIRIS";
export const UPDATE_GIRIS = "UPDATE_GIRIS";
export const POST_GIRIS = "POST_GIRIS";
export const SHOW_GIRIS_DETAIL_FORM = "SHOW_GIRIS_DETAIL_FORM";
export const SET_SELECTED_GIRIS = "SET_SELECTED_GIRIS";