const GET_HARCAMA_TURLERI = "GET_HARCAMA_TURLERI";
const DELETE_HARCAMA_TURU = "DELETE_HARCAMA_TURU";
const UPDATE_HARCAMA_TURU = "UPDATE_HARCAMA_TURU";
const POST_HARCAMA_TURU = "POST_HARCAMA_TURU";
const SHOW_HARCAMA_TURU_DETAIL_FORM = "SHOW_HARCAMA_TURU_DETAIL_FORM";
const SET_SELECTED_HARCAMA_TURU = "SET_SELECTED_HARCAMA_TURU";

export default { GET_HARCAMA_TURLERI, DELETE_HARCAMA_TURU, UPDATE_HARCAMA_TURU, POST_HARCAMA_TURU, SHOW_HARCAMA_TURU_DETAIL_FORM, SET_SELECTED_HARCAMA_TURU }